server:
  port: 8080

spring:
  cloud:
    config:
      #仓库的分支
      label: master
      server:
        default-application-name: @pom.artifactId@
        git:
          #git仓库地址
          uri: https://github.com/foxiswho/foxwho-config-repo
          #仓库路径
          search-paths: demo
          #访问git仓库的用户名
          username:
          #访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          password:

